# MATH 307   Applications of Linear Algebra

In this course we will use Python to solve and analyse linear equation with the help of a computer. 
This small *Introduction* will show you how you can use Python on your computer and give you a first glimps of what it is capable off. There are many Python tutorials in the internet and the best way to learn a new (programming *language* is to get out there and play around with it. 

We will mainly use the Python libraries NumPy, Matplotlib, SciPy and SymPy.In order to use them we need to import them 

## SymPy

In [1]:
import sympy as sy

Now we can use all the commands and function in the SymPy (symbolic computations) library in the following way

In [42]:
M = sy.Matrix([[2,1,1],[2,0,2],[4,3,4]])

In [43]:
M

Matrix([
[2, 1, 1],
[2, 0, 2],
[4, 3, 4]])

We have defined a symbolic Matrix. Why symbolic? We will come to that later. Lets first see what we can do with this Matrix. 

In [17]:
M.shape

(3, 3)

In [18]:
M.row(0)

Matrix([[2, 1, 1]])

In [19]:
M.col(-1)

Matrix([
[1],
[2],
[4]])

In [44]:
M.col_del(1)

In [49]:
M

Matrix([
[ 2,  1],
[ 2,  2],
[-1, -2],
[ 4,  4]])

In [31]:
M = M.row_insert(-1, Matrix([-1,-2,-3]))

NameError: name 'Matrix' is not defined

An error, such an error tells us a lot! Lets see what the problem is. 
It does not know the name 'Matrix' and it is clear why, we did not specify that Matrix belongs to the SymPy library. 
Lets try it again 

In [48]:
M = M.row_insert(2, sy.Matrix([[-1, -2]]))

In [50]:
M

Matrix([
[ 2,  1],
[ 2,  2],
[-1, -2],
[ 4,  4]])

In [51]:
M = M.col_insert(2, sy.Matrix([6, 7 ,8]))

ShapeError: `self` and `other` must have the same number of rows.

Oh no, another error. We can see that the size of the column we want to insert is wrong. But why? 

In [52]:
M.shape

(4, 2)

Ah our matrix is now 4 by 2. So we actually need to insert columns of size 4 

In [53]:
M = M.col_insert(2, sy.Matrix([6, 7 ,8, 0]))

In [54]:
M

Matrix([
[ 2,  1, 6],
[ 2,  2, 7],
[-1, -2, 8],
[ 4,  4, 0]])

**Lets do some Math:**

In [72]:
M = sy.Matrix([[2,1,1],[2,0,2],[4,3,4]])
N = sy.Matrix([[3,0,2],[1,-3,4],[-2,1,0]])

Addition and substraction of Matrices

In [74]:
M+N

Matrix([
[5,  1, 3],
[3, -3, 6],
[2,  4, 4]])

In [ ]:
M-N

Scalar Multiplication 

In [59]:
3*M

Matrix([
[ 6, 3,  3],
[ 6, 0,  6],
[12, 9, 12]])

Calculations with Matrices

In [60]:
2*M - 6*N

Matrix([
[-14,  2, -10],
[ -2, 18, -20],
[ 20,  0,   8]])

Matrix Multiplication

In [ ]:
M*M

In [62]:
M**2

Matrix([
[10,  5,  8],
[12,  8, 10],
[30, 16, 26]])

The Inverse of a matrix

In [64]:
V = N**-1

In [65]:
N*V

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [76]:
M.col_del(0)

In [77]:
M

Matrix([
[1, 1],
[0, 2],
[3, 4]])

Transpose of a Matrix

In [78]:
M.T

Matrix([
[1, 0, 3],
[1, 2, 4]])

*More operations for matrices*

In [80]:
sy.eye(4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [82]:
sy.zeros(2,3)

Matrix([
[0, 0, 0],
[0, 0, 0]])

In [83]:
sy.ones(3,2)

Matrix([
[1, 1],
[1, 1],
[1, 1]])

In [85]:
sy.diag(1,2,3)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [88]:
M = sy.Matrix([[2,1,1],[2,0,2],[4,3,4]])

In [89]:
M

Matrix([
[2, 1, 1],
[2, 0, 2],
[4, 3, 4]])

In [90]:
M.det()

-6

In [91]:
M.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

Note that this command returns a Matrix and a tuple of indices of the pivot columns

In [92]:
(M1,T1) = M.rref()

In [93]:
M1



Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [94]:
T1

(0, 1, 2)

This is a boring example, lets take a more intersting one: 

In [96]:
N = sy.Matrix([[2,-4,-3,-1],[1,-2,4,5],[-1,2,1,0]])

In [98]:
(N1,T1) = N.rref()

In [99]:
N1

Matrix([
[1, -2, 0, 1],
[0,  0, 1, 1],
[0,  0, 0, 0]])

In [100]:
T1

(0, 2)

In [103]:
N.nullspace()

[Matrix([
 [2],
 [1],
 [0],
 [0]]),
 Matrix([
 [-1],
 [ 0],
 [-1],
 [ 1]])]

In [104]:
N.columnspace()

[Matrix([
 [ 2],
 [ 1],
 [-1]]),
 Matrix([
 [-3],
 [ 4],
 [ 1]])]

We see that we can already do a lot with SymPy. However, as was said in the beginning this library is for symbolic calculations, not numerical ones. For example 

In [107]:
sy.sqrt(8)

2*sqrt(2)

That is the correct answer, but not a numerical value we can work with in a computer since $\sqrt 2$ is irrational

In [2]:
import numpy as np

In [3]:
np.sqrt(8)

2.8284271247461903

This is an approximate solution, however one which is accurate enough on a computer where we will always make errors due to the machine precision. 

*What is NumPy* and what can it do?

## NumPy

[NumPy](http://www.numpy.org/) is the core Python package for numerical computing. The main features of NumPy are:

* $N$-dimensional array object `ndarray`
* Vectorized operations and functions which broadcast across arrays for fast computation


**Creating Arrays**

The function `numpy.array` creates a NumPy array from a Python sequence such as a list, a tuple or a list of lists. For example, create a 1D NumPy array from a Python list:

In [4]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Notice that when we print a NumPy array it looks a lot like a Python list except that the entries are separated by spaces whereas entries in a Python list are separated by commas:

In [5]:
print([1,2,3,4,5])

[1, 2, 3, 4, 5]


Notice also that a NumPy array is displayed slightly differently when output by a cell (as opposed to being explicitly printed to output by the `print` function):

In [6]:
a

array([1, 2, 3, 4, 5])

Use the built-in function `type` to verify the type:

In [9]:
type(a)

numpy.ndarray

In [10]:
M = np.array([[1,2,3],[4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [11]:
type(M)

numpy.ndarray

how much should be introduced here? It is all in Patricks introduction

## Linear Algebra with SciPy

In [3]:
import scipy.linalg as la

In [16]:
A = np.array([[2,1,1],[2,0,2],[4,3,4]])
b = np.array([[-1],[1],[1]])

In [5]:
A.rref()

AttributeError: 'numpy.ndarray' object has no attribute 'rref'

This does not work, there is no rref function in np

In [17]:
M = sy.Matrix(A)

In [8]:
M.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

This works, but how can we now make numerical computations with M? 
Note we can also use A but this is just to show you how to transform a sy.Matrix to a np.array and vise versa.

In [18]:
B = np.array(M).astype(np.float64)

This transforms the datatype of M to an np.array and we can use it as usual with np.arrays. 

In [19]:
la.solve(B,b)

array([[-1.16666667],
       [-0.33333333],
       [ 1.66666667]])

**Lets do another example**

In [20]:
A1 = np.array([[2, 4, 6],[1, 1, 4]])
b1 = np.array([[2], [1]])

In [21]:
la.solve(A1,b1)

ValueError: Input a needs to be a square matrix.

NumPy has problems with non-square matrices and to solve such a system we unfortunately have to use least square methods 
# (Note: We need to have this in mind when we set up problems!!!)

In [22]:
np.linalg.lstsq(A1,b1,rcond=-1)

(array([[0.07407407],
        [0.18518519],
        [0.18518519]]),
 array([], dtype=float64),
 2,
 array([8.51531337, 1.22042541]))

... this is probably already to much for the first introduction. 