## How much python do I need to know for Quiz 2?

You should be able to set up and solve linear systems numerically using np.array and la.solve from the libraries NumPy and SciPy. For example, to solve 

$$\begin{bmatrix}1& 2& 3& 4\\4& 3& 2& 1\\1&2&2&1\\0&1&0&0\\\end{bmatrix} x =\begin{bmatrix}1\\1\\1\\1\\\end{bmatrix}$$

we can use np.array and la.solve from NumPy and SciPy like this:

In [30]:
import numpy as np
import scipy.linalg as la
A=np.array([[1, 2, 3, 4],[4, 3, 2, 1],[1,2,2,1],[0,1,0,0]])
b=np.array([[1],[1],[1],[1]])
x=la.solve(A,b)

All the standard operations on matrices are availabl in these libraries. For homework and "real life" you should get used to consulting the online documentation. For the quizzes I'll try to keep things under control!

## Finite differnce equations for boundary values problems with a parameter.

The Quiz will have a question on the this topic. I realized that there was more information needed than could be reasonalby absorbed in the few minutes available on a quiz. So I will give everyone a copy of this a few days before.

Let $\lambda > 0$ be a positive real number. We want to solve the BVP
$$-f''(x) -\lambda^2 f(x) = 0,\quad \hbox{ for } \quad x\in[0,1] \quad f(0)=f(1)=0$$ 

This sure looks like (and in fact is) a second order BVP like the ones we considered in class. It is different, though. For one thing, it is a homogeneous equation. If $f(x)$ solves this equation then so does any multiple of $f$. In particular, $f(0) = 0$ is always a solution. 

In fact this equation is so simple we can find all the solutions by brain. The general solution to $y'' - \lambda^2 y = 0$ is $y(x) = c_1 \cos(\lambda x) + c_2 \sin(\lambda x)$ The boundary conditions force $c_1=0$ and $\lambda = n\pi$ for $n\in\mathbb Z$. So solutions only exists for a discrete set of $\lambda$.

Suppose that when faced with this equation we try to proceed numerically by choosing a value of $\lambda$ and following our previous recipe. Well this is almost certainly doomed to failure unless we are lucky enough to have chosen one of the special values. It is like finding eigenvectors and eigenvalues. In fact, this equation *is* an infinite dimensional 
eigenvalue problem. In the quiz, you will use this insight to compute solutions.

## python procedures to understand coming in to the quizz


To compute equally spaced point you can use 

np.arange() 

returns evenly spaced values within a given interval.

np.linspace()

returns evenly spaced numbers over a specified interval. The procedures range() and linspace() are subtly different. Sometimes one is more convenient, sometimes the other 

np.diag()

If v is an one dimensional array (ie a vector) then np.diag(v) returns the matrix with $v$ on its diagonal.
Similarly, np.diag(v,1) is the matrix with v on its superdiagonal. Guess what np.diag(v,-1) is! Note that if $v$ has length $n$ then np.diag(v,1) is an $n+1)x(n+1) matrix. 

la.eig()

If A is an nxn matrix then la.eig(A) is an array with two components. 
la.eig[0] a one dimensional array (ie a vector)  containing the eigenvalues, 
while la.eig[1] has the eigenvectors of $A$ as columns.  So we can extract the spectral information of A as follows:

To define $A$ lets use np.diag to get some practice

In [32]:
v = np.arange(5)
vv =np.ones(3)
A = np.diag(v) - np.diag(vv,2) - np.diag(vv,-2) 
print(A)

[[ 0.  0. -1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [-1.  0.  2.  0. -1.]
 [ 0. -1.  0.  3.  0.]
 [ 0.  0. -1.  0.  4.]]


lets compute the eigenvalues/vectors and  pick the 2nd eigenvalues/vector pair.
eigvv has all the information,
eigvals condtains the eigenvalues
eigvects condtains the eigenvectors
ev2 and v2 are the second eigenvalue/eigenvector pair.

In [21]:
eigvv = la.eig(A)
eigvals = eigvv[0]
eigvecs = eigvv[1]
ev2= eigval[2]
v2 = eigvec[:,2]
print(ev2*v2 - A@v2)

[-9.99200722e-16-1.55431223e-15j  1.99840144e-15+1.44328993e-15j
 -5.55111512e-17+2.35922393e-16j -1.11022302e-16+6.10622664e-16j]


In [ ]:
Finally, since the eigenvalues are not always stored in increasing order we have to search for the bottom eigenvalue. 
For this we can use 

np.min()

returns the leftmost value (ie the minimum, if all the values are positive())

np.argmin(v) 

returns the index where the min occurs


In [29]:
v=np.array([1.1, 4.6, -2.0, 3.0])
np.min(v)
k=np.argmin(v)
v[k]

-2.0