Last time we discussed how we can use the SymPy Library. We saw that it is useful for symbolic calculation but has problems if we are interested in the acutal numeric value.

*Today we talk about NumPy and the linear algebra subpackage SciPy [`scipy.linalg`]*

## Part 2: NumPy

In [2]:
import numpy as np

### NumPy Arrays

Let's begin with a quick review of [NumPy arrays](../../scipy/numpy/). We can think of a 1D NumPy array as a list of numbers. We can think of a 2D NumPy array as a matrix. And we can think of a 3D array as a cube of numbers.
When we select a row or column from a 2D NumPy array, the result is a 1D NumPy array (called a [slice](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing)). This is different from MATLAB where when you select a column from a matrix it's returned as a column vector which is a 2D MATLAB matrix.

It can get a bit confusing and so we need to keep track of the shape, size and dimension of our NumPy arrays.

#### Array Attributes

Create a 1D (one-dimensional) NumPy array and verify its dimensions, shape and size.

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


Verify the number of dimensions:

In [3]:
a.ndim

1

Verify the shape of the array:

In [4]:
a.shape

(4,)

The shape of an array is returned as a [Python tuple](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences). The output in the cell above is a tuple of length 1. And we verify the size of the array (ie. the total number of entries in the array):

In [5]:
a.size

4

Create a 2D (two-dimensional) NumPy array (ie. matrix):

In [6]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


Verify the number of dimensions:

In [7]:
M.ndim

2

Verify the shape of the array:

In [8]:
M.shape

(3, 2)

Finally, verify the total number of entries in the array:

In [9]:
M.size

6

Select a row or column from a 2D NumPy array and we get a 1D array:

In [10]:
col = M[:,1] 
print(col)

[2 7 5]


Verify the number of dimensions of the slice:

In [11]:
col.ndim

1

Verify the shape and size of the slice:

In [12]:
col.shape

(3,)

In [13]:
col.size

3

When we select a row of column from a 2D NumPy array, the result is a 1D NumPy array. However, we may want to select a column as a 2D column vector. This requires us to use the [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) method.

For example, create a 2D column vector from the 1D slice selected from the matrix `M` above:

In [14]:
print(col)

[2 7 5]


In [15]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


Verify the dimensions, shape and size of the array:

In [16]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


The variables `col` and `column` are different types of objects even though they have the "same" data.

In [17]:
print(col)

[2 7 5]


In [18]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


### Matrix Operations and Functions

In [3]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [4]:
N = np.array([[1,2],[3,4]])
print(N)

[[1 2]
 [3 4]]


#### Arithmetic Operations

Recall that arithmetic [array operations](../scipy/numpy/#operations-and-functions) `+`, `-`, `/`, `*` and `**` are performed elementwise on NumPy arrays. Let's create a NumPy array and do some computations:

In [5]:
N + M

array([[4, 6],
       [2, 9]])

In [6]:
N-M

array([[-2, -2],
       [ 4, -1]])

In [7]:
3*M

array([[ 9, 12],
       [-3, 15]])

In [8]:
2*M - 4*N

array([[  2,   0],
       [-14,  -6]])

**Attention !!!**

In [10]:
print(M)

[[ 3  4]
 [-1  5]]


In [20]:
M * M

array([[ 9, 16],
       [ 1, 25]])

#### Matrix Multiplication

We use the `@` operator to do matrix multiplication with NumPy arrays:

In [21]:
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's compute $2I + 3A - AB$ for

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

and $I$ is the identity matrix of size 2:

In [22]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [23]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [24]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [25]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

#### Matrix Powers

There's no symbol for matrix powers and so we must import the function `matrix_power` from the subpackage `numpy.linalg`.

In [26]:
from numpy.linalg import matrix_power as mpow

In [27]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [28]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [29]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

Compare with the matrix multiplcation operator:

In [30]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [31]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [32]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

####  Tranpose

We can take the transpose with `.T` attribute:

In [33]:
print(M)

[[ 3  4]
 [-1  5]]


In [34]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


Notice that $M M^T$ is a symmetric matrix:

In [35]:
M @ M.T

array([[25, 17],
       [17, 26]])

#### Trace

We can find the trace of a matrix using the function `numpy.trace`:

In [38]:
np.trace(A)

5

### Exercise

Compute the matrix equation $AB + 2B^2 - I$ for matrices $A = \begin{bmatrix} 3 & 4 \\\ -1 & 2 \end{bmatrix}$ and $B = \begin{bmatrix} 5 & 2 \\\ 8 & -3 \end{bmatrix}$.              

**Now lets see how we can solve a linear systems with the help of Numpy and the linear algebra subpackage of SciPy** 